-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 21:39:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADOS` (
  `idEMPLEADOS` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Puesto` VARCHAR(45) NULL,
  PRIMARY KEY (`idEMPLEADOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENTAS` (
  `idVENTAS` INT NOT NULL,
  `Fecha` DATETIME NULL,
  `Total` DECIMAL(2) NULL,
  `VENTAScol` VARCHAR(45) NULL,
  `EMPLEADOS_idEMPLEADOS` INT NOT NULL,
  PRIMARY KEY (`idVENTAS`),
  INDEX `fk_VENTAS_EMPLEADOS1_idx` (`EMPLEADOS_idEMPLEADOS` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_EMPLEADOS1`
    FOREIGN KEY (`EMPLEADOS_idEMPLEADOS`)
    REFERENCES `mydb`.`EMPLEADOS` (`idEMPLEADOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SATISFACCION_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SATISFACCION_CLIENTE` (
  `VENTAS_idVENTAS` INT NOT NULL,
  `Satisfaccón_idResultado` VARCHAR(45) NULL,
  `EMPLEADOS_idEMPLEADOS` INT NOT NULL,
  `CLIENTES_idclientes` INT NOT NULL,
  PRIMARY KEY (`VENTAS_idVENTAS`, `EMPLEADOS_idEMPLEADOS`, `CLIENTES_idclientes`),
  INDEX `fk_SATISFACCION_CLIENTE_EMPLEADOS1_idx` (`EMPLEADOS_idEMPLEADOS` ASC) VISIBLE,
  CONSTRAINT `fk_SATISFACCION_CLIENTE_EMPLEADOS1`
    FOREIGN KEY (`EMPLEADOS_idEMPLEADOS`)
    REFERENCES `mydb`.`EMPLEADOS` (`idEMPLEADOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTES` (
  `idClientes` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `Correo Electrónico` VARCHAR(45) NULL,
  `Teléfono` VARCHAR(45) NULL,
  `VENTAS_idVENTAS` INT NOT NULL,
  `` INT NULL,
  PRIMARY KEY (`idClientes`, `VENTAS_idVENTAS`),
  INDEX `fk_CLIENTES_VENTAS_idx` (`VENTAS_idVENTAS` ASC) VISIBLE,
  INDEX `fk_CLIENTES_SATISFACCION_CLIENTE1_idx` (`` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTES_VENTAS`
    FOREIGN KEY (`VENTAS_idVENTAS`)
    REFERENCES `mydb`.`VENTAS` (`idVENTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTES_SATISFACCION_CLIENTE1`
    FOREIGN KEY (``)
    REFERENCES `mydb`.`SATISFACCION_CLIENTE` (`VENTAS_idVENTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTOS` (
  `idPRODUCTOS` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripción` VARCHAR(45) NULL,
  `Precio` DECIMAL(2) NULL,
  PRIMARY KEY (`idPRODUCTOS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENTAS_has_PRODUCTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENTAS_has_PRODUCTOS` (
  `VENTAS_idVENTAS` INT NOT NULL,
  `PRODUCTOS_idPRODUCTOS` INT NOT NULL,
  PRIMARY KEY (`VENTAS_idVENTAS`, `PRODUCTOS_idPRODUCTOS`),
  INDEX `fk_VENTAS_has_PRODUCTOS_PRODUCTOS1_idx` (`PRODUCTOS_idPRODUCTOS` ASC) VISIBLE,
  INDEX `fk_VENTAS_has_PRODUCTOS_VENTAS1_idx` (`VENTAS_idVENTAS` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_has_PRODUCTOS_VENTAS1`
    FOREIGN KEY (`VENTAS_idVENTAS`)
    REFERENCES `mydb`.`VENTAS` (`idVENTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_has_PRODUCTOS_PRODUCTOS1`
    FOREIGN KEY (`PRODUCTOS_idPRODUCTOS`)
    REFERENCES `mydb`.`PRODUCTOS` (`idPRODUCTOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo Electrónico` VARCHAR(45) NULL,
  `Teléfono` INT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `idVentas` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Total` FLOAT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idVentas`, `Empleado_idEmpleado`, `Clientes_idClientes`),
  INDEX `fk_VENTAS_EMPLEADO1_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  INDEX `fk_Ventas_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_EMPLEADO1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `idProductos` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(45) NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_Ventas` (
  `Ventas_idVentas` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Descuento` FLOAT NULL,
  PRIMARY KEY (`Ventas_idVentas`, `Productos_idProductos`),
  INDEX `fk_VENTAS_has_PRODUCTOS1_PRODUCTOS1_idx` (`Productos_idProductos` ASC) VISIBLE,
  INDEX `fk_VENTAS_has_PRODUCTOS1_VENTAS1_idx` (`Ventas_idVentas` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_has_PRODUCTOS1_VENTAS1`
    FOREIGN KEY (`Ventas_idVentas`)
    REFERENCES `mydb`.`Ventas` (`idVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_has_PRODUCTOS1_PRODUCTOS1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `mydb`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Satisfacción_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Satisfacción_Cliente` (
  `idSatisfacción_Cliente` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Puntos` INT(5) NOT NULL,
  PRIMARY KEY (`idSatisfacción_Cliente`),
  INDEX `fk_Clientes_has_Empleado_Empleado1_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  INDEX `fk_Clientes_has_Empleado_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_has_Empleado_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_Empleado_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
