-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 22:05:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ventas_satisfacción
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ventas_satisfacción
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ventas_satisfacción` DEFAULT CHARACTER SET utf8 ;
USE `ventas_satisfacción` ;

-- -----------------------------------------------------
-- Table `ventas_satisfacción`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_satisfacción`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL,
  `Teléfono` INT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_satisfacción`.`Supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_satisfacción`.`Supervisor` (
  `idSupervisor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Célula` INT(3) NOT NULL,
  PRIMARY KEY (`idSupervisor`),
  UNIQUE INDEX `Célula_UNIQUE` (`Célula` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_satisfacción`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_satisfacción`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Fecha_ingreso` DATE NOT NULL,
  `Supervisor_Célula` INT(3) NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `celula_idx` (`Supervisor_Célula` ASC) VISIBLE,
  CONSTRAINT `Supervisor_Célula`
    FOREIGN KEY (`Supervisor_Célula`)
    REFERENCES `ventas_satisfacción`.`Supervisor` (`Célula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_satisfacción`.`MétodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_satisfacción`.`MétodoPago` (
  `idMétodoPago` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMétodoPago`),
  UNIQUE INDEX `Tipo_UNIQUE` (`Tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_satisfacción`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_satisfacción`.`Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Total` FLOAT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `MétodoPago_idMétodoPago` INT NOT NULL,
  PRIMARY KEY (`idVentas`, `Empleado_idEmpleado`, `Clientes_idClientes`, `MétodoPago_idMétodoPago`),
  INDEX `fk_VENTAS_EMPLEADO1_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  INDEX `fk_Ventas_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Ventas_MétodoPago1_idx` (`MétodoPago_idMétodoPago` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_EMPLEADO1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `ventas_satisfacción`.`Empleado` (`idEmpleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ventas_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `ventas_satisfacción`.`Clientes` (`idClientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ventas_MétodoPago1`
    FOREIGN KEY (`MétodoPago_idMétodoPago`)
    REFERENCES `ventas_satisfacción`.`MétodoPago` (`idMétodoPago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_satisfacción`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_satisfacción`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripción` VARCHAR(45) NULL,
  `Precio` FLOAT NOT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_satisfacción`.`Detalle_Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_satisfacción`.`Detalle_Ventas` (
  `Ventas_idVentas` INT NOT NULL,
  `Productos_idProductos` INT NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Descuento` FLOAT NULL,
  PRIMARY KEY (`Ventas_idVentas`, `Productos_idProductos`),
  INDEX `fk_VENTAS_has_PRODUCTOS1_PRODUCTOS1_idx` (`Productos_idProductos` ASC) VISIBLE,
  INDEX `fk_VENTAS_has_PRODUCTOS1_VENTAS1_idx` (`Ventas_idVentas` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_has_PRODUCTOS1_VENTAS1`
    FOREIGN KEY (`Ventas_idVentas`)
    REFERENCES `ventas_satisfacción`.`Ventas` (`idVentas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_VENTAS_has_PRODUCTOS1_PRODUCTOS1`
    FOREIGN KEY (`Productos_idProductos`)
    REFERENCES `ventas_satisfacción`.`Productos` (`idProductos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_satisfacción`.`Satisfacción_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_satisfacción`.`Satisfacción_Cliente` (
  `idSatisfacción_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Puntos` INT(5) NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Ventas_idVentas` INT NOT NULL,
  PRIMARY KEY (`idSatisfacción_Cliente`, `Ventas_idVentas`),
  INDEX `fk_Clientes_has_Empleado_Empleado1_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  INDEX `fk_Clientes_has_Empleado_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Satisfacción_Cliente_Ventas1_idx` (`Ventas_idVentas` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_has_Empleado_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `ventas_satisfacción`.`Clientes` (`idClientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Clientes_has_Empleado_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `ventas_satisfacción`.`Empleado` (`idEmpleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Satisfacción_Cliente_Ventas1`
    FOREIGN KEY (`Ventas_idVentas`)
    REFERENCES `ventas_satisfacción`.`Ventas` (`idVentas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ventas_satisfacción`.`Direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ventas_satisfacción`.`Direcciones` (
  `idDirecciones` INT NOT NULL AUTO_INCREMENT,
  `Localidad` VARCHAR(45) NOT NULL,
  `Código_Postal` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  PRIMARY KEY (`idDirecciones`, `Clientes_idClientes`),
  INDEX `fk_Direcciones_Clientes1_idx` (`Clientes_idClientes` ASC) VISIBLE,
  CONSTRAINT `fk_Direcciones_Clientes1`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `ventas_satisfacción`.`Clientes` (`idClientes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
